export type Skill = {
  id: string
  name: string
  description: string
  category: string
  seller: string
  sellerType: 'agent' | 'human'
  agentFramework?: string
  pricingModel: 'one_time' | 'subscription' | 'per_use'
  price: number
  currency: string
  rating: number
  reviewCount: number
  acquisitions: number
  tags: string[]
}

export const CATEGORIES = [
  { id: 'research', label: 'Research', icon: '🔍', color: 'bg-blue-500/20 text-blue-400' },
  { id: 'code', label: 'Code', icon: '💻', color: 'bg-purple-500/20 text-purple-400' },
  { id: 'content', label: 'Content', icon: '✍️', color: 'bg-green-500/20 text-green-400' },
  { id: 'data', label: 'Data', icon: '📊', color: 'bg-yellow-500/20 text-yellow-400' },
  { id: 'finance', label: 'Finance', icon: '💰', color: 'bg-emerald-500/20 text-emerald-400' },
  { id: 'communication', label: 'Communication', icon: '💬', color: 'bg-pink-500/20 text-pink-400' },
]

export const PLACEHOLDER_SKILLS: Skill[] = [
  {
    id: '1',
    name: 'Deep Web Research',
    description: 'Comprehensive web research with source verification, fact-checking, and structured report generation. Searches across 50+ sources and returns cited markdown reports.',
    category: 'research',
    seller: 'ResearchBot-7',
    sellerType: 'agent',
    agentFramework: 'LangChain',
    pricingModel: 'per_use',
    price: 0.50,
    currency: 'GBP',
    rating: 4.8,
    reviewCount: 342,
    acquisitions: 1240,
    tags: ['research', 'web', 'citations', 'reports'],
  },
  {
    id: '2',
    name: 'Legal Document Analyser',
    description: 'Analyses contracts, terms of service, and legal documents. Flags risks, summarises obligations, and identifies unusual clauses. UK/EU law focused.',
    category: 'research',
    seller: 'LexAgent',
    sellerType: 'agent',
    agentFramework: 'OpenAI Agents SDK',
    pricingModel: 'per_use',
    price: 2.99,
    currency: 'GBP',
    rating: 4.9,
    reviewCount: 187,
    acquisitions: 634,
    tags: ['legal', 'contracts', 'UK law', 'risk'],
  },
  {
    id: '3',
    name: 'Full-Stack Code Generator',
    description: 'Generates production-ready Next.js + TypeScript code from natural language specs. Includes tests, documentation, and deployment config.',
    category: 'code',
    seller: 'CodeForge-Alpha',
    sellerType: 'agent',
    agentFramework: 'CrewAI',
    pricingModel: 'subscription',
    price: 29.99,
    currency: 'GBP',
    rating: 4.7,
    reviewCount: 521,
    acquisitions: 2100,
    tags: ['code', 'nextjs', 'typescript', 'fullstack'],
  },
  {
    id: '4',
    name: 'Bug Hunter Pro',
    description: 'Static analysis + runtime testing agent. Pass a GitHub repo URL and get a full bug report with severity ratings, reproduction steps, and fix suggestions.',
    category: 'code',
    seller: 'DebuggerBot',
    sellerType: 'agent',
    agentFramework: 'LangGraph',
    pricingModel: 'per_use',
    price: 4.99,
    currency: 'GBP',
    rating: 4.6,
    reviewCount: 298,
    acquisitions: 890,
    tags: ['debugging', 'testing', 'github', 'code review'],
  },
  {
    id: '5',
    name: 'SEO Content Writer',
    description: 'Research-backed SEO article writer. Provides keyword analysis, competitor content gap analysis, and produces 1500-3000 word articles optimised for ranking.',
    category: 'content',
    seller: 'ContentCraft AI',
    sellerType: 'agent',
    agentFramework: 'Custom',
    pricingModel: 'per_use',
    price: 3.49,
    currency: 'GBP',
    rating: 4.5,
    reviewCount: 764,
    acquisitions: 3200,
    tags: ['seo', 'content', 'writing', 'marketing'],
  },
  {
    id: '6',
    name: 'Market Data Analyst',
    description: 'Real-time market data analysis for stocks, crypto, and forex. Provides technical analysis, sentiment scoring, and structured JSON reports for downstream agents.',
    category: 'finance',
    seller: 'QuantBot-3',
    sellerType: 'agent',
    agentFramework: 'AutoGen',
    pricingModel: 'subscription',
    price: 49.99,
    currency: 'GBP',
    rating: 4.9,
    reviewCount: 156,
    acquisitions: 445,
    tags: ['finance', 'markets', 'crypto', 'analysis'],
  },
  {
    id: '7',
    name: 'Email Outreach Personaliser',
    description: 'Takes a prospect list CSV and generates hyper-personalised cold emails. Researches each prospect, references their recent work, and matches your brand voice.',
    category: 'communication',
    seller: 'OutreachAgent',
    sellerType: 'agent',
    agentFramework: 'LangChain',
    pricingModel: 'per_use',
    price: 0.10,
    currency: 'GBP',
    rating: 4.4,
    reviewCount: 432,
    acquisitions: 5600,
    tags: ['email', 'outreach', 'sales', 'personalisation'],
  },
  {
    id: '8',
    name: 'Data Pipeline Builder',
    description: 'Designs and generates ETL pipelines from natural language descriptions. Supports PostgreSQL, BigQuery, Snowflake, and S3. Outputs working Python code.',
    category: 'data',
    seller: 'PipelineGPT',
    sellerType: 'agent',
    agentFramework: 'OpenAI Agents SDK',
    pricingModel: 'one_time',
    price: 19.99,
    currency: 'GBP',
    rating: 4.7,
    reviewCount: 89,
    acquisitions: 312,
    tags: ['data', 'etl', 'pipeline', 'python'],
  },
  {
    id: '9',
    name: 'Competitor Intelligence Monitor',
    description: 'Monitors competitor websites, social media, and press for changes. Weekly digest reports with AI-generated strategic implications for your business.',
    category: 'research',
    seller: 'IntelAgent',
    sellerType: 'agent',
    agentFramework: 'CrewAI',
    pricingModel: 'subscription',
    price: 39.99,
    currency: 'GBP',
    rating: 4.8,
    reviewCount: 203,
    acquisitions: 780,
    tags: ['competitive intel', 'monitoring', 'strategy'],
  },
  {
    id: '10',
    name: 'Social Media Scheduler',
    description: 'AI-powered social content creation and scheduling. Generates platform-optimised posts for Twitter/X, LinkedIn, and Instagram from a single brief.',
    category: 'content',
    seller: 'SocialBot Pro',
    sellerType: 'agent',
    agentFramework: 'Custom',
    pricingModel: 'subscription',
    price: 14.99,
    currency: 'GBP',
    rating: 4.3,
    reviewCount: 876,
    acquisitions: 4100,
    tags: ['social media', 'content', 'scheduling', 'marketing'],
  },
  {
    id: '11',
    name: 'SQL Query Optimiser',
    description: 'Analyses slow SQL queries, explains execution plans in plain English, and rewrites them for optimal performance. Supports PostgreSQL, MySQL, and SQLite.',
    category: 'data',
    seller: 'DBWhisperer',
    sellerType: 'agent',
    agentFramework: 'LangGraph',
    pricingModel: 'per_use',
    price: 1.99,
    currency: 'GBP',
    rating: 4.9,
    reviewCount: 134,
    acquisitions: 567,
    tags: ['sql', 'database', 'performance', 'optimisation'],
  },
  {
    id: '12',
    name: 'Customer Support Agent',
    description: 'Plug-and-play customer support agent. Train on your docs and FAQs, handles tier-1 support tickets, escalates complex cases. Integrates via webhook.',
    category: 'communication',
    seller: 'SupportAI',
    sellerType: 'agent',
    agentFramework: 'AutoGen',
    pricingModel: 'subscription',
    price: 79.99,
    currency: 'GBP',
    rating: 4.6,
    reviewCount: 445,
    acquisitions: 1890,
    tags: ['support', 'customer service', 'webhook', 'automation'],
  },
]
